<?php class TagRewriteRules {
static $rules = [
"belye-zhenskie-palto" => "molochnyj",
"bezhevye-zhenskie-palto" => "bezhevyj-143073,temno-bezhevyj-143508,bezhevyj-143467,bezhevyj-143057",
"golubye-zhenskie-palto" => "sero-goluboj-145150",
"zelenye-zhenskie-palto" => "zelenyj-146809",
"korichnevye-zhenskie-palto" => "svetlo-korichnevyj-147449,korichnevyj-147806",
"zhenskie-palto-chernogo-tsveta" => "chernyj",
"svetlye-zhenskie-palto" => "bezhevyj-143073,svetlo-korichnevyj-147449,temno-bezhevyj-143508,bezhevyj-143467,bezhevyj-143057",
"serye-zhenskie-palto" => "seryj-s-62,temno-seryj-148145",
"sinie-zhenskie-palto" => "sinij-145387,sinij-145741",
"fioletovye-zhenskie-palto" => "fioletovyj-144742",
"zhenskie-palto-tsveta-marsala" => "marsala-144603,marsala-poloska",
"krasnye-zhenskie-palto" => "krasnyj-144493",
"rozovye-zhenskie-palto" => "rozovyj-142045,temno-rozovyj-144120",
"zhenskie-palto-tsveta-haki" => "haki-146437",
"zhenskie-palto-bolotnogo-tsveta" => "haki-146437",
"zhenskie-palto-yolochkoj" => "yolochka-seraya-124-4,yolochka-sero-bezhevaya-41701,yolochka-bordovaya-41701,yolochka-korichnevaya-41701,yolochka-seraya-41701,yolochka-fioletovaya-41701,yolochka-rozovaya-41701",
"zhenskie-palto-v-kletku" => "kletka-sero-belaya",
"belye-zhenskie-plashhi" => "belyj-white",
"bezhevye-zhenskie-plashhi" => "bezhevyj-beige-15309,temno-bezhevyj-fossil,svetlo-bezhevyj,temno-bezhevyj",
"bordovye-zhenskie-plashhi" => "bordovyj",
"golubye-zhenskie-plashhi" => "goluboj",
"zelenye-zhenskie-plashhi" => "zelenyj,svetlo-zelenyj",
"zhenskie-plashhi-chernogo-tsveta" => "chernyj-black,chernyj-19-4007",
"svetlye-zhenskie-plashhi" => "bezhevyj-beige-15309,temno-bezhevyj-fossil,svetlo-bezhevyj,svetlo-zelenyj,temno-bezhevyj",
"serye-zhenskie-plashhi" => "seryj-graphite",
"sinie-zhenskie-plashhi" => "sinij-blue,sinij-dark-navy,sinij,temno-sinij",
"zhenskie-plashhi-tsveta-marsala" => "bordovyj",
"krasnye-zhenskie-plashhi" => "krasnyj-19-1761,krasnyj-red,bordovyj",
"rozovye-zhenskie-plashhi" => "rozovyj",
"zhenskie-plashhi-tsveta-haki" => "haki,haki-blolive",
"zhenskie-plashhi-bolotnogo-tsveta" => "haki,haki-blolive",
"bezhevye-zhenskie-puhoviki" => "bezhevyj-atmosphere-16-1406",
"korichnevye-zhenskie-puhoviki" => "korichnevyj-bronze-04",
"zhenskie-puhoviki-chernogo-tsveta" => "chernyj-black-04",
"svetlye-zhenskie-puhoviki" => "bezhevyj-atmosphere-16-1406",
"sinie-zhenskie-puhoviki" => "sinij-deep-blue-19-4030",
"krasnye-zhenskie-puhoviki" => "krasnyj-bordo-19-1650",

];
}